// <auto-generated />
using System;
using KasaManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KasaManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KasaManagerDbContext))]
    [Migration("20260404173746_AddImmutableSnapshotAuditFields")]
    partial class AddImmutableSnapshotAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.CalculationParityDrift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AbsoluteDifference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DataFirstValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KasaScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LegacyValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonHint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResolutionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RootCauseCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TargetDate", "KasaScope", "FieldKey")
                        .HasDatabaseName("IX_ParityDrift_Date_Scope_Key");

                    b.ToTable("CalculationParityDrifts", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.DailyCalculationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArchivedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("DailyCalculationResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ForDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputsFingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KasaTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyCalculationResultId")
                        .HasDatabaseName("IX_DailyCalcHistory_ResultId");

                    b.HasIndex("ForDate", "KasaTuru", "VersionNumber")
                        .HasDatabaseName("IX_DailyCalcHistory_Date_Type_Ver");

                    b.ToTable("DailyCalculationHistories", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.DailyCalculationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalculatedVersion")
                        .HasColumnType("int");

                    b.Property<string>("CalculationEngineVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CarryOverPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ForDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormulaSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputsFingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStale")
                        .HasColumnType("bit");

                    b.Property<string>("KasaTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PreviousResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreviousResultId")
                        .HasDatabaseName("IX_DailyCalcResults_PrevId");

                    b.HasIndex("ForDate", "KasaTuru")
                        .HasDatabaseName("IX_DailyCalcResults_Date_Type");

                    b.ToTable("DailyCalculationResults", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.DailyFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ForDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SourceColumnNo")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SourceRowNo")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ForDate", "CanonicalKey")
                        .HasDatabaseName("IX_DailyFacts_Date_Key");

                    b.ToTable("DailyFacts", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.DailyOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ForDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ForDate", "CanonicalKey")
                        .HasDatabaseName("IX_DailyOverrides_Date_Key");

                    b.ToTable("DailyOverrides", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.DataFirstTrustSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DriftCount")
                        .HasColumnType("int");

                    b.Property<int>("ExactMatchCount")
                        .HasColumnType("int");

                    b.Property<string>("KasaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StaleCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetDate", "KasaType")
                        .IsUnique()
                        .HasDatabaseName("IX_TrustSnapshots_Date_Scope");

                    b.ToTable("DataFirstTrustSnapshots", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Calculation.Data.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImportProfileVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TargetDate")
                        .HasDatabaseName("IX_ImportBatches_TargetDate");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Entities.ComparisonDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAciklamaSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("BankaTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OnlineBirimAdi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OnlineDosyaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OnlineMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("OriginalConfidence")
                        .HasColumnType("float");

                    b.Property<string>("OriginalMatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonType", "OnlineDosyaNo", "OnlineMiktar", "OnlineBirimAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_ComparisonDecisions_UniqueRecord")
                        .HasFilter("[OnlineBirimAdi] IS NOT NULL");

                    b.ToTable("ComparisonDecisions");
                });

            modelBuilder.Entity("KasaManager.Domain.FinancialExceptions.FinansalIstisna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("BeklenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CozulmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("EtkiYonu")
                        .HasColumnType("int");

                    b.Property<decimal>("GerceklesenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HedefHesapAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HesapTuru")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KararDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KararTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("KararVerenKullanici")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("Neden")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OlusturmaTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentIstisnaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SistemGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SistemeGirilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IslemTarihi", "Durum", "KararDurumu")
                        .HasDatabaseName("IX_FinansalIstisnalar_Tarih_Durum_Karar");

                    b.ToTable("FinansalIstisnalar", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FinancialExceptions.FinansalIstisnaHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventKullanici")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("EventTarihiUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("FinansalIstisnaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NewBeklenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NewDurum")
                        .HasColumnType("int");

                    b.Property<decimal?>("NewGerceklesenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NewKararDurumu")
                        .HasColumnType("int");

                    b.Property<decimal?>("NewSistemeGirilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldBeklenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OldDurum")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldGerceklesenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OldKararDurumu")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldSistemeGirilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventTarihiUtc")
                        .HasDatabaseName("IX_FinExHistory_EventTarihi");

                    b.HasIndex("FinansalIstisnaId")
                        .HasDatabaseName("IX_FinExHistory_IstisnaId");

                    b.ToTable("FinansalIstisnaHistory", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "SortOrder");

                    b.ToTable("FormulaLines", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "RunAtUtc");

                    b.ToTable("FormulaRuns", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SelectedInputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "IsActive");

                    b.ToTable("FormulaSets", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.UserFieldPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("KasaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SelectedFieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("KasaType", "UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_UserFieldPreferences_KasaType_UserName")
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("UserFieldPreferences", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Identity.KasaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_KasaUsers_Username");

                    b.ToTable("KasaUsers", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.HesapKontrol.HesapKontrolKaydi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("AnalizTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirimAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CozulmeKaynakId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CozulmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DosyaNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("GeriAlanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeriAlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HesapTuru")
                        .HasColumnType("int");

                    b.Property<int?>("KarsilastirmaSatirIndex")
                        .HasColumnType("int");

                    b.Property<string>("KarsilastirmaTuru")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("KullaniciOnay")
                        .HasColumnType("bit");

                    b.Property<string>("Notlar")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnaylayanKullanici")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonBildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TakipBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TespitEdilenTip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_HesapKontrol_Durum");

                    b.HasIndex("AnalizTarihi", "HesapTuru", "Durum")
                        .HasDatabaseName("IX_HesapKontrol_Tarih_Hesap_Durum");

                    b.ToTable("HesapKontrolKayitlari", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.CalculatedKasaSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalculatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FinancialExceptionsSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FormulaSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormulaSetName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KasaRaporDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KasaTuru")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OutputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_CalculatedKasaSnapshots_IsDeleted");

                    b.HasIndex("RaporTarihi", "KasaTuru", "IsActive")
                        .HasDatabaseName("IX_CalculatedKasaSnapshots_Date_Type_Active");

                    b.ToTable("CalculatedKasaSnapshots", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaporTuru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SelectionTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceEvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WarningsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RaporTarihi", "RaporTuru");

                    b.ToTable("KasaRaporSnapshots", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotInputs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .IsUnique();

                    b.ToTable("KasaRaporSnapshotInputs", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .IsUnique();

                    b.ToTable("KasaRaporSnapshotResults", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSummaryRow")
                        .HasColumnType("bit");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Veznedar")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("KasaRaporSnapshotRows", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Settings.KasaGlobalDefaultsSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefaultBozukPara")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultDundenDevredenKasaNakit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DefaultGenelKasaBaslangicTarihiSeed")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DefaultGenelKasaDevredenSeed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultKasaEksikFazla")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultKaydenTahsilat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultNakitPara")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HesapAdiHarc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HesapAdiMasraf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HesapAdiStopaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanHarc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanMasraf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanPostaPulu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanStopaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedVeznedarlarJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("VergideBirikenSeed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VergideBirikenSeedUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KasaGlobalDefaultsSettings", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.Validation.DismissedValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DismissedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("KasaTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RaporTarihi", "KasaTuru", "RuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_DismissedValidations_Date_Kasa_Rule");

                    b.ToTable("DismissedValidations", (string)null);
                });

            modelBuilder.Entity("KasaManager.Domain.FinancialExceptions.FinansalIstisnaHistory", b =>
                {
                    b.HasOne("KasaManager.Domain.FinancialExceptions.FinansalIstisna", null)
                        .WithMany()
                        .HasForeignKey("FinansalIstisnaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaLine", b =>
                {
                    b.HasOne("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaSet", "Set")
                        .WithMany("Lines")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaRun", b =>
                {
                    b.HasOne("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaSet", "Set")
                        .WithMany("Runs")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotInputs", b =>
                {
                    b.HasOne("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshot", "Snapshot")
                        .WithOne("Inputs")
                        .HasForeignKey("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotInputs", "SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotResults", b =>
                {
                    b.HasOne("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshot", "Snapshot")
                        .WithOne("Results")
                        .HasForeignKey("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotResults", "SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshotRow", b =>
                {
                    b.HasOne("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshot", "Snapshot")
                        .WithMany("Rows")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("KasaManager.Domain.FormulaEngine.Authoring.PersistedFormulaSet", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("KasaManager.Domain.Reports.Snapshots.KasaRaporSnapshot", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Results");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
